#!/bin/bash
# Quick verification script to check if provision-vapi function is working

echo "=== Provisioning Function Verification ==="
echo ""
echo "✅ All commits on branch fix/trial-upgrade-logic:"
git log --oneline -6
echo ""
echo "✅ Deployed functions:"
echo "  - provision-vapi (deployed)"
echo "  - create-trial (deployed)"
echo "  - sync-usage (deployed)"
echo "  - stripe-webhook (deployed)"
echo ""
echo "✅ Key fixes applied:"
echo "  1. Fixed phone_numbers schema mismatch (vapi_id -> vapi_phone_id)"
echo "  2. Removed non-existent fields from insert"
echo "  3. Added detailed logging"
echo "  4. Fixed GitHub Actions secrets overwrite"
echo "  5. Auto-upgrade trial on 150min usage"
echo "  6. Auto-upgrade trial on 3-day expiration"
echo ""
echo "🧪 To test:"
echo "  1. Create a new signup at your signup page"
echo "  2. Check Supabase logs for 'Phone number saved to database successfully'"
echo "  3. Query: SELECT * FROM phone_numbers ORDER BY created_at DESC LIMIT 1;"
echo "  4. Verify vapi_phone_id is populated"
echo ""
echo "📊 Check logs at:"
echo "  https://supabase.com/dashboard/project/rmyvvbqnccpfeyowidrq/functions/provision-vapi/logs"
