export interface AreaCodeOption {
  code: string;
  label: string;
}

export const COMMON_AREA_CODES: AreaCodeOption[] = [
  { code: "205", label: "Birmingham, AL" },
  { code: "206", label: "Seattle, WA" },
  { code: "212", label: "New York, NY" },
  { code: "213", label: "Los Angeles, CA" },
  { code: "214", label: "Dallas, TX" },
  { code: "303", label: "Denver, CO" },
  { code: "305", label: "Miami, FL" },
  { code: "312", label: "Chicago, IL" },
  { code: "317", label: "Indianapolis, IN" },
  { code: "404", label: "Atlanta, GA" },
  { code: "407", label: "Orlando, FL" },
  { code: "408", label: "San Jose, CA" },
  { code: "415", label: "San Francisco, CA" },
  { code: "480", label: "Phoenix, AZ" },
  { code: "512", label: "Austin, TX" },
  { code: "602", label: "Phoenix, AZ" },
  { code: "617", label: "Boston, MA" },
  { code: "619", label: "San Diego, CA" },
  { code: "650", label: "Silicon Valley, CA" },
  { code: "702", label: "Las Vegas, NV" },
  { code: "703", label: "Northern Virginia" },
  { code: "704", label: "Charlotte, NC" },
  { code: "713", label: "Houston, TX" },
  { code: "720", label: "Denver Suburbs, CO" },
  { code: "801", label: "Salt Lake City, UT" },
  { code: "805", label: "Central Coast, CA" },
  { code: "808", label: "Hawaii" },
  { code: "816", label: "Kansas City, MO" },
  { code: "832", label: "Greater Houston, TX" },
  { code: "901", label: "Memphis, TN" },
  { code: "904", label: "Jacksonville, FL" },
  { code: "907", label: "Alaska" },
  { code: "909", label: "Inland Empire, CA" },
  { code: "912", label: "Savannah, GA" },
  { code: "913", label: "Kansas City, KS" },
  { code: "916", label: "Sacramento, CA" },
  { code: "917", label: "New York City, NY" },
  { code: "918", label: "Tulsa, OK" },
  { code: "919", label: "Raleigh, NC" },
  { code: "949", label: "Orange County, CA" },
  { code: "971", label: "Portland, OR" },
  { code: "972", label: "Dallas–Fort Worth, TX" },
  { code: "980", label: "Charlotte Metro, NC" },
  { code: "985", label: "Houma, LA" },
  { code: "986", label: "Idaho" },
];
