-- RPC: get_recent_calls is now defined in migration 20251216000004
-- with expanded signature. Later migrations further extend the schema.
-- This file previously attempted to define an outdated version.
